repo = "github.com/morya/go_aes_crypto_sample"
rule = "reassigned-error"
sha = "5673c80805a70d3c398fd7d27130eab1ac9bc595"

[[issues]]
  fileline = 13
  filepath = "aes.go"
  fixed = false
  ignored = "fp. investigate"
